name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'

jobs:
  sync-repo-to-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone Wiki Repository # Wikiリポジトリをクローン
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

    - name: Sync docs to Wiki # docフォルダをWikiに同期
      run: |
        rsync -av --delete doc/ wiki/

        # 変更があった場合のみ同期
        cd wiki
        git add .
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -m "Sync docs from repository to Wiki"
          git push
        else
          echo "No changes detected."
        fi
